# Generated by Django 4.0.5 on 2022-07-01 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_collection_featured_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='unit_price',
        ),
    ]
